---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: patroni
    cluster-name: {{ include "patroni-postgres.fullname" . }}
  name: {{ include "patroni-postgres.fullname" . }}-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: patroni
    cluster-name: {{ include "patroni-postgres.fullname" . }}
  name: {{ include "patroni-postgres.fullname" . }}-leader
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: patroni
    cluster-name: {{ include "patroni-postgres.fullname" . }}
  name: {{ include "patroni-postgres.fullname" . }}-sync
