apiVersion: v1
stringData:
  {{- with .Values.superuserpassword }}
  superuser-password: {{ . }}
  {{- end }}
  {{- with .Values.replicationpassword }}
  replication-password: {{ . }}
  {{- end }}
kind: Secret
metadata:
  labels:
    application: patroni
    cluster-name: {{ include "patroni-postgres.fullname" . }}
  name: {{ include "patroni-postgres.fullname" . }}
