---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "patroni-postgres.serviceAccountName" . }}
  labels:
    {{- include "patroni-postgres.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "patroni-postgres.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "patroni-postgres.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "patroni-postgres.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "patroni-postgres.serviceAccountName" . }}
