apiVersion: v1
kind: Service
metadata:
  name: {{ include "patroni-postgres.serviceName" . }}
  labels:
    {{- include "patroni-postgres.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
  selector:
    application: patroni
    cluster-name: {{ include "patroni-postgres.fullname" . }}
    role: master
    {{- include "patroni-postgres.selectorLabels" . | nindent 4 }}
